UseParametric: true
nClasses: 4  # signal + TT + DY + SM_Higgs
activation: tanh
batch_size: 1000
dropout: 0.2
features: # Log everything in GeV, then later we will divide by 4-body mass (m_bbll)
  - lep1_pt
  - lep1_phi
  - lep1_eta
  # - lep1_legType # Change to type

  - lep2_pt
  - lep2_phi
  - lep2_eta
  # - lep2_legType

  - PuppiMET_pt
  - PuppiMET_phi

  - HT

  - ll_dR
  - bb_dR
  - ll_bb_dR

  - ll_dphi
  - jj_dphi

  - met_ll_dphi
  - met_bb_dphi

  - MT
  - total_MT
  - lep1_MT
  - lep2_MT
  - MT2_ll
  - MT2_bb
  - MT2_blbl
  - MT2_blbl2

  - ll_mass

  - bb_CosTheta

  # - bjet1_pt
  # - bjet1_phi
  # - bjet1_eta
  # - bjet1_mass
  # - bjet1_btagPNetB

  # - bjet2_pt
  # - bjet2_phi
  # - bjet2_eta
  # - bjet2_mass
  # - bjet2_btagPNetB

  - fatbjet_pt
  - fatbjet_phi
  - fatbjet_eta
  - fatbjet_mass_PNetCorr

  - fatbjet_tau1
  - fatbjet_tau2
  - fatbjet_tau3
  - fatbjet_tau4
  - fatbjet_msoftdrop
  # - fatbjet_neMultiplicity
  # - fatbjet_neHEF
  # - fatbjet_nConstituents
  # - fatbjet_muEF
  # - fatbjet_neEmEF

  - nExtraLeps
  - nExtraTau

  # - DoubleLep_DeepHME_mass
  # - DoubleLep_DeepHME_mass_log
  # - DoubleLep_DeepHME_mass_error_rel # Relative error (error/mass)

  # - channelId
gamma1: 2
gamma2: 0.5
learning_rate: 0.0005
lr_decay: 0.1
lr_patience: 20
l2_rate: 0.001
loss_scale: 0.2
n_layers: 5
n_units: 512
n_units_reduction_ratio: 1.0
n_epochs: 100
parametric_list:
  - 300
  - 400
  - 500
  - 550
  - 600
  - 650
  - 700
  - 800
  - 900
  - 1000
  - 1200
  - 1400
  - 1600
  - 1800
  - 2000
  - 2500
  - 3000
  - 3500
  - 4000
patience: 100
use_batch_norm: true
use_film: false
weight_decay: 0.004
